#!/bin/bash

echo "========================================="
echo "🎯 Test de la fonctionnalité d'upload d'images"
echo "========================================="
echo ""
echo "📌 URLs à tester :"
echo "   - Admin Services: http://localhost/DENTISTE/admin/services"
echo "   - Login Admin: http://localhost/DENTISTE/admin/login"
echo ""
echo "🔑 Identifiants admin :"
echo "   Email: admin@cabinet-dupont.fr"
echo "   Mot de passe: Admin123!"
echo ""
echo "✅ Service de test créé :"
echo "   ID: 9"
echo "   Titre: Test Service avec Image"
echo "   Image: /DENTISTE/assets/images/couronne-dentaire.jpg"
echo ""
echo "📝 Pour tester l'upload :"
echo "   1. Se connecter à l'admin"
echo "   2. Aller sur 'Services'"
echo "   3. Cliquer sur '+ Ajouter un service'"
echo "   4. Remplir le formulaire et sélectionner une image"
echo "   5. L'image devrait s'afficher dans le tableau"
echo ""
echo "🔍 Vérification des fichiers :"
ls -lh /c/xampp/htdocs/DENTISTE/public/assets/images/*.jpg 2>/dev/null
echo ""
echo "📂 Dossier services :"
ls -lh /c/xampp/htdocs/DENTISTE/public/assets/images/services/ 2>/dev/null || echo "   (vide - prêt pour les uploads)"
echo ""
echo "========================================="
